@url = http://localhost:3000

###
# @name token
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailproject&username=alveselton@gmail.com&password=123456&grant_type=password

###
@access_token = {{token.response.body.access_token}}

###

GET {{url}}/ping

###
# @name campanha
POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "notebook Lenovo",
    "content" : "Notebook",
    "emails" : ["elton2004@hotmail.com"]
}

###
@id_campaign = {{campanha.response.body.id}}

##


GET {{url}}/campaigns
Authorization: Bearer {{access_token}}

###

GET {{url}}/campaigns/{{id_campaign}}
Authorization: Bearer {{access_token}}

###

PATCH {{url}}/campaigns/cancel/{{id_campaign}}
Authorization: Bearer {{access_token}}

###

DELETE {{url}}/campaigns/delete/{{id_campaign}}
Authorization: Bearer {{access_token}}

###

PATCH {{url}}/campaigns/start/{{id_campaign}}
Authorization: Bearer {{access_token}}